
name: myfirstworkflow

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Welcome Message
              run: |
               echo 'My firt GithubAction Job'
               ls -ltr
               pwd
               cat readme.md

            - name: Generate ASCII Text at Work
              run: cowsay -f dragon "Run for cover, I am dragon....RAWR" >> dragon.txt 

            

            
