
name: Generate ASCII Text

on: 
  workflow_dispatch: 

jobs:
    first-job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Building the job
              run: |
               ls  -ltra 
               sudo apt-get install cowsay -y
               cowsay -f dragon "Run for cover, I am dragon....RAWR" >> dragon.txt
               sleep 10
            - name: upload the artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

            

    second-job:
        needs: first-job
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download the artifact
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file
                

            - name: Image Build check
              run: |
                grep -i "dragon" dragon.txt
                sleep 10
              
               
    third-job:
        needs: second-job
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download the artifact
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file
                

            - name: Printing file
              run: |
               echo 'Deploying......'
               cat dragon.txt     
             

            

            
