
name: Generate ASCII Text

on: push

jobs:
    first-job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Building the job
              run: |
               ls  -ltra 
               sudo apt-get install cowsay -y
               cowsay -f dragon "Run for cover, I am dragon....RAWR" >> dragon.txt
               sleep 30

            

    second-job:
        needs: first-job
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Image Build check
              run: |
                grep -i "dragon" dragon.txt
                sleep 10
              
               
    third-job:
        needs: second-job
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Printing file
              run: |
               echo 'Deploying......'
               cat dragon.txt     
             

            

            
