
name: Generate ASCII Text

on: push

jobs:
    first-job:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: List the files
              run: ls  -ltra  

            - name: Executing shell script
              run: |
               chmod +x shells-script.sh
               ./shells-script.sh 
              
             

            

            
