name: Matrix configuration
on:
  push:
  workflow_dispatch: 
   

jobs:
  
   deploys-on-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-word, alpine]
    runs-on: ${{ matrix.os}}
    steps:
    - name: echo docker details
      run: docker info

    - name: runs image on ${{ matrix.image}}  
      run: docker run ${{matrix.image}}
   