name: Matrix configuration
on:
  push:
  workflow_dispatch: 
   

jobs:
  
   deploys-on-ubuntu:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-word, alpine]
        exclude:
          - image: alpine
            os: windows-latest
        include:
          - image: amd64/alpine
            os: ubuntu-latest

    runs-on: ${{ matrix.os}}
    steps:
    - name: echo docker details
      run: docker info

    - name: runs image on ${{ matrix.image}}  
      run: docker run ${{matrix.image}}
   