name: Explore Varibale and Secretes
on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
    
        -   name: build docker
            env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: apa234
                IMAGE_NAME: github-action:latest
                DOCKER_PASSWORD: ajhsdbrj
            run: docker build -t {{ env.CONTAINER_REGISTRY}}/{{env.DOCKER_USERNAME}}/{{env.IMAGE_NAME}}
        -   name: docker login
            run: docker login --username={{env.DOCKER_USERNAME}} --password={{env.DOCKER_PASSWORD}}
        -   name: docker publish
            run: docker push {{env.CONTAINER_REGISTRY}}/{{env.DOCKER_USERNAME}}/{{env.DOCKER_PASSWORD}}
            
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        -    name:  docker run
             run: docker run -d -p 8080:80 {{env.CONTAINER_REGISTRY}}/{{env.DOCKER_USERNAME}}/{{env.DOCKER_PASSWORD}}          
